name: "(CI): Verify Build And Plan"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Verify Directory and Go Mod
        run: |
          pwd
          ls

      - name: Setup GO 1.23.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
          cache-dependency-path: subdir/go.sum

      - name: Install Dependencies
        run: |
          go mod tidy

      - name: Run Build
        run: go build -v ./...

      - name: Build Docker Image
        run: |
          docker build -t hermes-api:latest .

          